# Default parameters for dataset and algorithm
defaults:
  - common
  - dataset: siftsmall
  - algo: annoy
  - specialized_param: ${defaults.1.dataset}_${defaults.2.algo}
    optional: true

# Directories for data
interim: ./interim
output: ./output

# flags
num_trial: 10
